name: pyre

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  pyre:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install cython flask flask_cors graphql-core typing_inspect
          VERSION=$(grep "version" .pyre_configuration | sed -n -e 's/.*\(0\.0\.[0-9]*\).*/\1/p')
          pip install pyre-check-nightly==$VERSION

      - name: Run Pyre
        continue-on-error: true
        run: |
          pyre -n --output=sarif check > sarif.json

      - name: Expose SARIF Results
        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
        with:
          name: SARIF Results
          path: sarif.json

      - name: Upload SARIF Results
        uses: github/codeql-action/upload-sarif@8214744c546c1e5c8f03dde8fab3a7353211988d # v3.26.7
        with:
          sarif_file: sarif.json

      - name: Fail Command On Errors
        run: |
          if [ "$(cat sarif.json | grep 'PYRE-ERROR')" != "" ]; then python -m json.tool sarif.json && exit 1; fi
